apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
        - name: application-service
          image: maxwellc21/application-service:latest
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              value: mongodb://mongo:27017/application-db
            - name: JWT_SECRET
              value: your_jwt_secret
